# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/49842/Desktop/zcu104_base/zcu104_base.srcs/sources_1/bd/zcu104_base/ip/zcu104_base_xbar_6/zcu104_base_xbar_6.xci
# IP: The module: 'zcu104_base_xbar_6' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/49842/Desktop/zcu104_base/zcu104_base.srcs/sources_1/bd/zcu104_base/ip/zcu104_base_xbar_6/zcu104_base_xbar_6_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'zcu104_base_xbar_6'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: c:/Users/49842/Desktop/zcu104_base/zcu104_base.srcs/sources_1/bd/zcu104_base/ip/zcu104_base_xbar_6/zcu104_base_xbar_6.xci
# IP: The module: 'zcu104_base_xbar_6' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/49842/Desktop/zcu104_base/zcu104_base.srcs/sources_1/bd/zcu104_base/ip/zcu104_base_xbar_6/zcu104_base_xbar_6_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'zcu104_base_xbar_6'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
